<a href="https://colab.research.google.com/github/garymcm/deep-learning/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import torch
import numpy as np


In [7]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [16]:
np1 = np.random.rand(3,4)
np1


array([[0.56726029, 0.68583255, 0.19124981, 0.7384562 ],
       [0.48602338, 0.61295934, 0.22486356, 0.85611441],
       [0.5126548 , 0.13483015, 0.67274525, 0.5211716 ]])

In [18]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.4375,  0.7062, -0.5474, -0.5340],
        [ 1.4945, -0.4547, -1.1563, -0.3874],
        [ 0.8859,  0.4501,  2.4297,  1.3291]])

In [20]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
## Create tensor from numpy array

my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5673, 0.6858, 0.1912, 0.7385],
        [0.4860, 0.6130, 0.2249, 0.8561],
        [0.5127, 0.1348, 0.6727, 0.5212]], dtype=torch.float64)