<a href="https://colab.research.google.com/github/garymcm/deep-learning/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [5]:
# Basic Math with tensors
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [7]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [8]:
# Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [10]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [12]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [13]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [15]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [17]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [18]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [20]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [21]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [23]:
# Exponent
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [26]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [27]:
# reassigment_
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [28]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [29]:
tensor_a

tensor([ 6,  8, 10, 12])