<a href="https://colab.research.google.com/github/garymcm/deep-learning/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# reshape and view
my_torch  = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
# Reshape if we don't know the number of items
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
my_torch2 = my_torch2.reshape(3, -1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [13]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
my_torch3 = my_torch3.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
my_torch4 = torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_torch5 = my_torch4.reshape((2,5))
my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
my_torch4[1] = 4141
my_torch4

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [22]:
my_torch5

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [23]:
# Slices

my_torch7 = torch.arange(10)


In [24]:
# Get and item
my_torch7[7]

tensor(7)

In [26]:
# Get a slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [27]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [28]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])